rocket-3/dbmss

.rultor.yml

Fixed Qulice running in rultor merge

---

src/main/java/org/fusionsoft/database/DbdFile.java
src/main/java/org/fusionsoft/database/snapshot/AstronomicalTime.java
src/main/java/org/fusionsoft/database/snapshot/DatabaseInfo.java
src/main/java/org/fusionsoft/database/snapshot/HashTextOfTime.java
src/main/java/org/fusionsoft/database/snapshot/ObjectNames.java

Try to fix 'todo' comments

---

.0pdd.yml

Added 0pdd config file

---

src/main/java/org/fusionsoft/database/DbdFile.java
src/main/java/org/fusionsoft/database/SnapshotCreateProcedure.java
src/main/java/org/fusionsoft/database/package-info.java
src/main/java/org/fusionsoft/database/snapshot/AstronomicalTime.java
src/main/java/org/fusionsoft/database/snapshot/ConfigurationTablesOfDbd.java
src/main/java/org/fusionsoft/database/snapshot/DatabaseInfo.java
src/main/java/org/fusionsoft/database/snapshot/DatabaseInfoOfDbd.java
src/main/java/org/fusionsoft/database/snapshot/DbGitRepoOfDbdFile.java
src/main/java/org/fusionsoft/database/snapshot/DbObjects.java
src/main/java/org/fusionsoft/database/snapshot/HashTextOfTime.java
src/main/java/org/fusionsoft/database/snapshot/ObjectNames.java
src/main/java/org/fusionsoft/database/snapshot/ObjectsFromServerMentionedInDbd.java
src/main/java/org/fusionsoft/database/snapshot/ObjectsWithNames.java
src/main/java/org/fusionsoft/database/snapshot/SnapshotFolder.java
src/main/java/org/fusionsoft/database/snapshot/Writable.java
src/main/java/org/fusionsoft/database/snapshot/writable/DbdYamlOfObjects.java
src/main/java/org/fusionsoft/database/snapshot/writable/SnapshotInfo.java
src/main/java/org/fusionsoft/database/snapshot/writable/TableDataFilesOfObjects.java
src/main/java/org/fusionsoft/lib/yaml/artefacts/KeysFromYamlNode.java

Rearrange puzzles

---

src/main/java/org/fusionsoft/database/DbdFile.java
src/main/java/org/fusionsoft/database/snapshot/DatabaseInfo.java

Split #45 into puzzles

---

src/main/java/org/fusionsoft/database/BaseYamlRepresentative.java
src/main/java/org/fusionsoft/database/MappingOfExampleYaml.java
src/main/java/org/fusionsoft/database/YamlRepresentative.java
src/main/java/org/fusionsoft/database/dbd/document/DbdServerYamlMapping.java
src/main/java/org/fusionsoft/database/dbd/document/fields/DbdServerFields.java
src/main/java/org/fusionsoft/database/dbd/document/fields/package-info.java
src/main/java/org/fusionsoft/database/dbd/document/package-info.java
src/main/java/org/fusionsoft/database/snapshot/DatabaseInfo.java
src/main/java/org/fusionsoft/database/snapshot/databaseinfo/DatabaseInfoOfDbd.java
src/main/java/org/fusionsoft/database/snapshot/databaseinfo/DbmsSignature.java
src/main/java/org/fusionsoft/database/snapshot/databaseinfo/DbmsSignatureOfServerMapping.java
src/main/java/org/fusionsoft/lib/yaml/YamlMappingHasKeys.java
src/main/java/org/fusionsoft/lib/yaml/YamlMappingOf.java
src/main/java/org/fusionsoft/lib/yaml/YamlMappingOfPath.java
src/main/java/org/fusionsoft/lib/yaml/YamlNodeOfPath.java
src/main/java/org/fusionsoft/lib/yaml/YamlNodeOfScalar.java
src/main/java/org/fusionsoft/lib/yaml/YamlNodeValidated.java
src/main/java/org/fusionsoft/lib/yaml/artefacts/TextOfMappingValue.java
src/test/java/org/fusionsoft/database/snapshot/databaseinfo/DatabaseInfoOfDbdTest.java
src/test/java/org/fusionsoft/database/snapshot/databaseinfo/package-info.java

Issue 64 dbinfo dbd

---

src/main/java/org/fusionsoft/database/SnapshotCreateProcedure.java
src/main/java/org/fusionsoft/database/dbdfile/package-info.java
src/main/java/org/fusionsoft/database/snapshot/AstronomicalTime.java
src/main/java/org/fusionsoft/database/snapshot/HashTextOf.java
src/main/java/org/fusionsoft/database/snapshot/SnapshotCatalogName.java
src/main/java/org/fusionsoft/database/snapshot/writable/SnapshotInfo.java

Designed and implemented AstronomicalTime contract
Separated and implemented HashTextOf(AstronomicalTime), SnapshotCatalogName

Designed and implemented AstronomicalTime, HashTextOf, SnapshotCatalogName

---

src/main/java/org/fusionsoft/database/Folder.java
src/main/java/org/fusionsoft/database/MappingEmpty.java
src/main/java/org/fusionsoft/database/SnapshotCreateProcedure.java
src/main/java/org/fusionsoft/database/Writable.java
src/main/java/org/fusionsoft/database/WritableYamlDocument.java
src/main/java/org/fusionsoft/database/WriteTo.java
src/main/java/org/fusionsoft/database/snapshot/CreatingSnapshotFolder.java
src/main/java/org/fusionsoft/database/snapshot/writable/DbdYamlOfObjects.java
src/main/java/org/fusionsoft/database/snapshot/writable/SnapshotInfo.java
src/main/java/org/fusionsoft/database/snapshot/writable/TableDataFilesOfObjects.java

Created Folder iface.
Refactored SnapshotFolder to new purpose name and Folder contract
Changed Writable to accept Folder
Created basic Writable - WritableYamlDocument
Refactored all Writable impls.

(#51) Writable implementations

---

pom.xml
src/main/java/org/fusionsoft/database/TextEnumValueOf.java
src/main/java/org/fusionsoft/database/snapshot/databaseinfo/DbmsSignature.java
src/main/java/org/fusionsoft/database/snapshot/databaseinfo/DbmsSignatureOfServerMapping.java

(#60) Implementation fix 

---

src/main/java/org/fusionsoft/database/DbdFile.java
src/main/java/org/fusionsoft/database/package-info.java

(#40) New puzzles added

---

src/main/java/org/fusionsoft/database/SnapshotCreateProcedure.java
src/main/java/org/fusionsoft/database/mapping/MappingEmpty.java
src/main/java/org/fusionsoft/database/mapping/MappingOfExampleYaml.java
src/main/java/org/fusionsoft/database/mapping/dbd/DbdServerMappingOfDbdFile.java
src/main/java/org/fusionsoft/database/mapping/dbd/DbdServerYamlMapping.java
src/main/java/org/fusionsoft/database/mapping/dbd/package-info.java
src/main/java/org/fusionsoft/database/mapping/fields/DbdServerFields.java
src/main/java/org/fusionsoft/database/mapping/fields/package-info.java
src/main/java/org/fusionsoft/database/mapping/package-info.java
src/main/java/org/fusionsoft/database/snapshot/DbmsSignature.java
src/main/java/org/fusionsoft/database/snapshot/databaseinfo/DatabaseInfoOfDbd.java
src/main/java/org/fusionsoft/database/snapshot/dbmssignature/DbmsSignatureName.java
src/main/java/org/fusionsoft/database/snapshot/dbmssignature/DbmsSignatureOfServerMapping.java
src/main/java/org/fusionsoft/database/snapshot/dbmssignature/package-info.java
src/main/java/org/fusionsoft/database/writable/DbdYamlOfObjects.java
src/main/java/org/fusionsoft/database/writable/SnapshotInfo.java
src/main/java/org/fusionsoft/database/writable/TableDataFilesOfObjects.java
src/main/java/org/fusionsoft/database/writable/WritableYamlDocument.java
src/main/java/org/fusionsoft/database/writable/package-info.java
src/test/java/org/fusionsoft/database/snapshot/databaseinfo/DatabaseInfoOfDbdTest.java

(#72) DbdServerYamlMapping extraction

---

.rultor.yml

- added pdd check before build
- changed docker image for possible faster variant
- rm unnecessary env options

Updated .rultor.yml

---

src/main/java/org/fusionsoft/database/SnapshotCreateProcedure.java
src/main/java/org/fusionsoft/database/mapping/dbd/DbdRootMapping.java
src/main/java/org/fusionsoft/database/mapping/dbd/DbdRootNodeValidation.java
src/main/java/org/fusionsoft/database/snapshot/DbObject.java
src/main/java/org/fusionsoft/database/snapshot/ObjectSignature.java
src/main/java/org/fusionsoft/database/snapshot/ObjectSignatures.java
src/main/java/org/fusionsoft/database/snapshot/ObjectType.java
src/main/java/org/fusionsoft/database/snapshot/Objects.java
src/main/java/org/fusionsoft/database/snapshot/objects/ObjectIsDbdConfigurationTablePredicate.java
src/main/java/org/fusionsoft/database/snapshot/objects/ObjectsFiltered.java
src/main/java/org/fusionsoft/database/snapshot/objects/ObjectsFromDatabase.java
src/main/java/org/fusionsoft/database/snapshot/objects/ObjectsFromServerMentionedInDbd.java
src/main/java/org/fusionsoft/database/snapshot/objects/ObjectsInDbdPredicate.java
src/main/java/org/fusionsoft/database/snapshot/objects/ObjectsOfDbdFile.java
src/main/java/org/fusionsoft/database/snapshot/objects/ObjectsOfDbdRootMapping.java
src/main/java/org/fusionsoft/database/snapshot/objects/ObjectsWithNamesPredicate.java
src/main/java/org/fusionsoft/database/snapshot/objects/package-info.java
src/main/java/org/fusionsoft/database/snapshot/objectsignature/NaiveObjectSignature.java
src/main/java/org/fusionsoft/database/snapshot/objectsignature/NamesOfObjects.java
src/main/java/org/fusionsoft/database/snapshot/objectsignature/ObjectsMentionedAsConfigTablesInDbd.java
src/main/java/org/fusionsoft/database/snapshot/objectsignature/package-info.java
src/main/java/org/fusionsoft/lib/yaml/YamlMappingOfScalar.java
src/test/java/org/fusionsoft/database/snapshot/databaseinfo/DatabaseInfoOfDbdTest.java

(#46) Created corresponding classes, fixed some file structure.

---

src/main/java/org/fusionsoft/database/mapping/fields/DbdSchemaFields.java
src/main/java/org/fusionsoft/database/mapping/fields/DdbTableFields.java
src/main/java/org/fusionsoft/database/snapshot/NaiveDbObject.java
src/main/java/org/fusionsoft/database/snapshot/ObjectType.java
src/main/java/org/fusionsoft/database/snapshot/objects/NamesJoined.java
src/main/java/org/fusionsoft/database/snapshot/objects/ObjectOfDbdConstraintMapping.java
src/main/java/org/fusionsoft/database/snapshot/objects/ObjectOfDbdIndexMapping.java
src/main/java/org/fusionsoft/database/snapshot/objects/ObjectsEnvelope.java
src/main/java/org/fusionsoft/database/snapshot/objects/ObjectsOfDbdConstraintsMapping.java
src/main/java/org/fusionsoft/database/snapshot/objects/ObjectsOfDbdIndexesMapping.java
src/main/java/org/fusionsoft/database/snapshot/objects/ObjectsOfDbdSchemaMapping.java
src/main/java/org/fusionsoft/database/snapshot/objects/ObjectsOfDbdSchemasMapping.java
src/main/java/org/fusionsoft/database/snapshot/objects/ObjectsOfDbdTableMapping.java
src/main/java/org/fusionsoft/database/snapshot/objects/ObjectsOfDbdTablesMapping.java
src/main/java/org/fusionsoft/database/snapshot/objectsignature/NaiveObjectSignature.java
src/main/java/org/fusionsoft/lib/yaml/YamlMappingOfPath.java
src/main/java/org/fusionsoft/lib/yaml/artefacts/MappingFromMappingIgnoreKeys.java
src/main/java/org/fusionsoft/lib/yaml/artefacts/MappingFromMappingKeys.java
src/main/java/org/fusionsoft/lib/yaml/artefacts/MaybeEmptyTextOf.java
src/main/java/org/fusionsoft/lib/yaml/artefacts/TextOfScalarNode.java
src/test/java/org/fusionsoft/database/snapshot/objects/ObjectsOfDbdRootMappingTest.java
src/test/java/org/fusionsoft/database/snapshot/objects/package-info.java

For issue #82 
Created all corresponding classed, now we can parse objects of DBD file. 
Table's data and validation is not implemented for now.

(#82) Implementation

---

src/main/java/org/fusionsoft/database/mapping/fields/DbdConstraintFields.java
src/main/java/org/fusionsoft/database/snapshot/objects/dbms/ConstraintOfResultSet.java
src/main/java/org/fusionsoft/database/snapshot/objects/dbms/ObjectsFromPostgres.java
src/main/java/org/fusionsoft/database/snapshot/objects/dbms/postgres/PgConstraints.java
src/main/java/org/fusionsoft/database/snapshot/query/MessageFormatQuery.java
src/main/java/org/fusionsoft/database/snapshot/query/PgColumnsQuery.java
src/main/java/org/fusionsoft/database/snapshot/query/PgConstraintsQuery.java
src/main/java/org/fusionsoft/database/snapshot/query/PgMessageFormatQuery.java
src/main/java/org/fusionsoft/database/snapshot/query/PgTablesQuery.java
src/main/java/org/fusionsoft/lib/yaml/MappingWithoutNullScalars.java
src/main/java/org/fusionsoft/lib/yaml/YamlScalarSequenceOfResultSet.java
src/test/java/org/fusionsoft/database/snapshot/objects/dbms/ObjectsFromServerTest.java
src/test/java/org/fusionsoft/database/snapshot/objects/dbms/postgres/PgConstraintsTest.java
src/test/java/org/fusionsoft/database/snapshot/objects/dbms/postgres/package-info.java
src/test/java/org/fusionsoft/database/snapshot/query/PgConstraintsQueryTest.java
src/test/java/org/fusionsoft/database/snapshot/query/package-info.java
src/test/java/org/fusionsoft/lib/yaml/MappingWithoutNullScalarsTest.java

Issue 112 constraints

---

src/main/java/org/fusionsoft/database/mapping/dbd/DbdSchemaMapping.java
src/main/java/org/fusionsoft/database/mapping/dbd/DbdSchemaMappingOfObjects.java
src/main/java/org/fusionsoft/database/mapping/dbd/DbdSequenceMapping.java
src/main/java/org/fusionsoft/database/mapping/dbd/DbdSequenceMappingOfObjects.java
src/main/java/org/fusionsoft/database/mapping/dbd/DbdSequencesMappingOfObjects.java
src/main/java/org/fusionsoft/database/mapping/entries/EntriesOfYamlRepresentative.java
src/main/java/org/fusionsoft/database/mapping/entries/EntriesWithKeys.java
src/main/java/org/fusionsoft/database/mapping/entries/EntriesWithoutKeys.java
src/main/java/org/fusionsoft/database/mapping/fields/DbdSchemaFields.java
src/main/java/org/fusionsoft/database/mapping/fields/DbdSequenceFields.java
src/main/java/org/fusionsoft/database/snapshot/objects/dbms/ObjectsFromPostgres.java
src/main/java/org/fusionsoft/database/snapshot/objects/dbms/SequenceOfResultSet.java
src/main/java/org/fusionsoft/database/snapshot/objects/dbms/postgres/PgConstraints.java
src/main/java/org/fusionsoft/database/snapshot/objects/dbms/postgres/PgIndexes.java
src/main/java/org/fusionsoft/database/snapshot/objects/dbms/postgres/PgSequences.java
src/main/java/org/fusionsoft/database/snapshot/query/PgSequencesQuery.java
src/main/java/org/fusionsoft/lib/yaml/EntriesOfYamlMapping.java
src/main/java/org/fusionsoft/lib/yaml/MappingWithoutNullScalars.java
src/test/java/org/fusionsoft/database/snapshot/objects/dbms/ObjectsFromServerTest.java
src/test/java/org/fusionsoft/database/snapshot/objects/dbms/postgres/PgSequencesTest.java
src/test/java/org/fusionsoft/database/snapshot/query/PgSequencesQueryTest.java
src/test/java/org/fusionsoft/lib/yaml/MappingWithoutNullScalarsNestedTest.java

Issue 109 pg sequences

---

src/main/java/org/fusionsoft/database/mapping/dbd/DbdSchemaMapping.java
src/main/java/org/fusionsoft/database/mapping/dbd/DbdTableMappingOfObjects.java
src/main/java/org/fusionsoft/database/mapping/dbd/DbdTableMappingWithChildObjects.java
src/main/java/org/fusionsoft/database/mapping/dbd/DbdTriggerMapping.java
src/main/java/org/fusionsoft/database/mapping/fields/DbdTableFields.java
src/main/java/org/fusionsoft/database/mapping/fields/DbdTriggerFields.java
src/main/java/org/fusionsoft/database/snapshot/objects/dbms/ObjectsFromPostgres.java
src/main/java/org/fusionsoft/database/snapshot/objects/dbms/TriggerOfResultSet.java
src/main/java/org/fusionsoft/database/snapshot/objects/dbms/postgres/PgTriggers.java
src/main/java/org/fusionsoft/database/snapshot/query/PgTriggersQuery.java
src/test/java/org/fusionsoft/database/snapshot/objects/dbms/ObjectsFromServerTest.java

Issue 116 pg triggers

---

src/main/java/org/fusionsoft/database/mapping/dbd/DbdFunctionMapping.java
src/main/java/org/fusionsoft/database/mapping/dbd/ofobjects/DbdFunctionsMappingOfObjects.java
src/main/java/org/fusionsoft/database/mapping/dbd/ofobjects/DbdSchemaMappingOfObjects.java
src/main/java/org/fusionsoft/database/mapping/fields/DbdFunctionFields.java
src/main/java/org/fusionsoft/database/mapping/fields/DbdSchemaFields.java
src/main/java/org/fusionsoft/database/snapshot/objects/dbms/FunctionOfResultSet.java
src/main/java/org/fusionsoft/database/snapshot/objects/dbms/ObjectsFromPostgres.java
src/main/java/org/fusionsoft/database/snapshot/objects/dbms/postgres/PgFunctions.java
src/main/java/org/fusionsoft/database/snapshot/query/pg/PgDomainConstraintsQuery.java
src/main/java/org/fusionsoft/database/snapshot/query/pg/PgFunctionsQuery.java
src/test/java/org/fusionsoft/database/snapshot/objects/dbms/ObjectsFromServerTest.java

Issue 115 snapshot functions

---

pom.xml
src/main/java/org/fusionsoft/database/mapping/dbd/DbdTupleAttributeMapping.java
src/main/java/org/fusionsoft/database/mapping/dbd/DbdTupleMapping.java
src/main/java/org/fusionsoft/database/mapping/dbd/ofobjects/DbdObjectsOfTypeMapping.java
src/main/java/org/fusionsoft/database/mapping/dbd/ofobjects/DbdSchemaMappingOfObjects.java
src/main/java/org/fusionsoft/database/mapping/dbd/ofobjects/DbdTableMappingWithChildObjects.java
src/main/java/org/fusionsoft/database/mapping/dbd/ofobjects/DbdTuplesMappingOfObjects.java
src/main/java/org/fusionsoft/database/mapping/entries/ScalarEntryOfResultSet.java
src/main/java/org/fusionsoft/database/mapping/fields/DbdSchemaFields.java
src/main/java/org/fusionsoft/database/mapping/fields/DbdTupleAttributeField.java
src/main/java/org/fusionsoft/database/mapping/fields/DbdTupleField.java
src/main/java/org/fusionsoft/database/snapshot/objects/dbms/ObjectsFromPostgres.java
src/main/java/org/fusionsoft/database/snapshot/objects/dbms/postgres/PgTuples.java
src/main/java/org/fusionsoft/database/snapshot/objects/resultset/ObjectOfEntries.java
src/main/java/org/fusionsoft/database/snapshot/objects/resultset/TableOfResultSet.java
src/main/java/org/fusionsoft/database/snapshot/objects/resultset/TupleAttributeMappingOfResultSet.java
src/main/java/org/fusionsoft/database/snapshot/objects/resultset/TupleOfResultSet.java
src/main/java/org/fusionsoft/database/snapshot/objectsignature/FullObjectNameOfResultSet.java
src/main/java/org/fusionsoft/database/snapshot/query/PgTupleAttributesQuery.java
src/main/java/org/fusionsoft/database/snapshot/query/pg/PgTuplesQuery.java
src/main/java/org/fusionsoft/lib/yaml/YamlScalarSequenceOfResultSet.java
src/test/java/org/fusionsoft/database/snapshot/objects/dbms/ObjectsFromServerTest.java
src/test/java/org/fusionsoft/database/snapshot/objects/dbms/dvdrental.yaml
src/test/java/org/fusionsoft/database/snapshot/objects/dbms/pagilla.yaml

Issue 111 tuples

---

src/main/java/org/fusionsoft/database/mapping/dbd/DbdEnumMapping.java
src/main/java/org/fusionsoft/database/mapping/dbd/ofobjects/DbdEnumsMappingOfObjects.java
src/main/java/org/fusionsoft/database/mapping/dbd/ofobjects/DbdSchemaMappingOfObjects.java
src/main/java/org/fusionsoft/database/mapping/fields/DbdEnumField.java
src/main/java/org/fusionsoft/database/mapping/fields/DbdSchemaFields.java
src/main/java/org/fusionsoft/database/snapshot/objects/dbms/ObjectsFromPostgres.java
src/main/java/org/fusionsoft/database/snapshot/objects/dbms/postgres/PgEnums.java
src/main/java/org/fusionsoft/database/snapshot/objects/dbms/postgres/package-info.java
src/main/java/org/fusionsoft/database/snapshot/objects/resultset/EnumOfResultSet.java
src/main/java/org/fusionsoft/database/snapshot/objects/resultset/package-info.java
src/main/java/org/fusionsoft/database/snapshot/query/pg/PgEnumsQuery.java
src/test/java/org/fusionsoft/database/snapshot/objects/dbms/ObjectsFromServerTest.java
src/test/java/org/fusionsoft/database/snapshot/objects/dbms/dvdrental.yaml
src/test/java/org/fusionsoft/database/snapshot/objects/dbms/pagilla.yaml

Issue 105 snapshot enums
